export const AUTHENTICATE_SUCCESS = "AUTHENTICATE_SUCCESS";
export const AUTHENTICATE_START = "AUTHENTICATE_START";
export const AUTHENTICATE_FAIL = "AUTHENTICATE_FAIL";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_START = "LOGIN_START";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const LOGOUT = "LOGOUT";

export const INITIAL_LOAD_COMPLETED = "INITIAL_LOAD_COMPLETED";
export const INITIAL_LOAD_RESET = "INITIAL_LOAD_RESET";

export const GENERATE_OTP_START = "GENERATE_OTP_START";
export const GENERATE_OTP_SUCCESS = "GENERATE_OTP_SUCCESS";
export const GENERATE_OTP_FAIL = "GENERATE_OTP_FAIL";

export const VALIDATE_OTP_START = "VALIDATE_OTP_START";
export const VALIDATE_OTP_FAIL = "VALIDATE_OTP_FAIL";
export const VALIDATE_OTP_SUCCESS = "VALIDATE_OTP_SUCCESS";

export const FETCH_APP_CONFIG_START = "FETCH_APP_CONFIG_START";
export const FETCH_APP_CONFIG_SUCCESS = "FETCH_APP_CONFIG_SUCCESS";
export const FETCH_APP_CONFIG_FAIL = "FETCH_APP_CONFIG_FAIL";

export const FETCH_USERINFO_START = "FETCH_USERINFO_START";
export const FETCH_USERINFO_SUCCESS = "FETCH_USERINFO_SUCCESS";
export const FETCH_USERINFO_FAIL = "FETCH_USERINFO_FAIL";

export const FETCH_SERVICES_START = "FETCH_SERVICES_START";
export const FETCH_SERVICES_SUCCESS = "FETCH_SERVICES_SUCCESS";
export const FETCH_SERVICES_FAIL = "FETCH_SERVICES_FAIL";

export const FETCH_SERVICETYPE_START = "FETCH_SERVICETYPE_START";
export const FETCH_SERVICETYPE_SUCCESS = "FETCH_SERVICETYPE_SUCCESS";
export const FETCH_SERVICETYPE_FAIL = "FETCH_SERVICETYPE_FAIL";

export const FETCH_PROMOS_START = "FETCH_PROMOS_START";
export const FETCH_PROMOS_SUCCESS = "FETCH_PROMOS_SUCCESS";
export const FETCH_PROMOS_FAIL = "FETCH_PROMOS_FAIL";

export const FETCH_LOCATION_START = "FETCH_LOCATION_START";
export const FETCH_LOCATION_SUCCESS = "FETCH_LOCATION_SUCCESS";
export const FETCH_LOCATION_FAIL = "FETCH_LOCATION_FAIL";

export const UPDATE_USERINFO_START = "UPDATE_USERINFO_START";
export const UPDATE_USERINFO_SUCCESS = "UPDATE_USERINFO_SUCCESS";
export const UPDATE_USERINFO_FAIL = "UPDATE_USERINFO_FAIL";

export const FETCH_USER_PATIENT_PROFILE_START =
  "FETCH_USER_PATIENT_PROFILE_START";
export const FETCH_USER_PATIENT_PROFILE_SUCCESS =
  "FETCH_USER_PATIENT_PROFILE_SUCCESS";
export const FETCH_USER_PATIENT_PROFILE_FAIL =
  "FETCH_USER_PATIENT_PROFILE_FAIL";

export const CRUD_USER_PATIENT_PROFILE_START =
  "CRUD_USER_PATIENT_PROFILE_START";
export const CRUD_USER_PATIENT_PROFILE_SUCCESS =
  "CRUD_USER_PATIENT_PROFILE_SUCCESS";
export const CRUD_USER_PATIENT_PROFILE_FAIL = "CRUD_USER_PATIENT_PROFILE_FAIL";

export const FETCH_USER_PATIENT_ADDRESS_START =
  "FETCH_USER_PATIENT_ADDRESS_START";
export const FETCH_USER_PATIENT_ADDRESS_SUCCESS =
  "FETCH_USER_PATIENT_ADDRESS_SUCCESS";
export const FETCH_USER_PATIENT_ADDRESS_FAIL =
  "FETCH_USER_PATIENT_ADDRESS_FAIL";

export const CRUD_USER_PATIENT_ADDRESS_START =
  "CRUD_USER_PATIENT_ADDRESS_START";
export const CRUD_USER_PATIENT_ADDRESS_SUCCESS =
  "CRUD_USER_PATIENT_ADDRESS_SUCCESS";
export const CRUD_USER_PATIENT_ADDRESS_FAIL = "CRUD_USER_PATIENT_ADDRESS_FAIL";

export const FETCH_SERVICEPACKAGE_START = "FETCH_SERVICEPACKAGE_START";
export const FETCH_SERVICEPACKAGE_SUCCESS = "FETCH_SERVICEPACKAGE_SUCCESS";
export const FETCH_SERVICEPACKAGE_FAIL = "FETCH_SERVICEPACKAGE_FAIL";

//Hari on 20191112
export const FETCH_SLOTS_START = "FETCH_SLOTS_START";
export const FETCH_SLOTS_SUCCESS = "FETCH_SLOTS_SUCCESS";
export const FETCH_SLOTS_FAIL = "FETCH_SLOTS_FAIL";

export const FETCH_SLOT_SERVICE_LOC_MAPP_START =
  "FETCH_SLOT_SERVICE_LOC_MAPP_START";
export const FETCH_SLOT_SERVICE_LOC_MAPP_SUCCESS =
  "FETCH_SLOT_SERVICE_LOC_MAPP_SUCCESS";
export const FETCH_SLOT_SERVICE_LOC_MAPP_FAIL =
  "FETCH_SLOT_SERVICE_LOC_MAPP_FAIL";
//20191122

//Hari on 20191216
export const SET_CURR_LOCATION_START = "SET_CURR_LOCATION_START";
export const SET_CURR_LOCATION_SUCCESS = "SET_CURR_LOCATION_SUCCESS";
export const SET_CURR_LOCATION_FAIL = "SET_CURR_LOCATION_FAIL";
//20191216

//Hari on 20191219
export const SAVE_USERLOGIN_LOG_START = "SAVE_USERLOGIN_LOG_START";
export const SAVE_USERLOGIN_LOG_SUCCESS = "SAVE_USERLOGIN_LOG_SUCCESS";
export const SAVE_USERLOGIN_LOG_FAIL = "SAVE_USERLOGIN_LOG_FAIL";

export const FETCH_NOTIFICATION_TMPL_START = "FETCH_NOTIFICATION_TMPL_START";
export const FETCH_NOTIFICATION_TMPL_SUCCESS =
  "FETCH_NOTIFICATION_TMPL_SUCCESS";
export const FETCH_NOTIFICATION_TMPL_FAIL = "FETCH_NOTIFICATION_TMPL_FAIL";

export const FETCH_PUSH_NOTIFICATION_START = "FETCH_PUSH_NOTIFICATION_START";
export const FETCH_PUSH_NOTIFICATION_SUCCESS =
  "FETCH_PUSH_NOTIFICATION_SUCCESS";
export const FETCH_PUSH_NOTIFICATION_FAIL = "FETCH_PUSH_NOTIFICATION_FAIL";
//20191219

export const FETCH_OTHERMASTER_GRADE_START = "FETCH_OTHERMASTER_GRADE_START";
export const FETCH_OTHERMASTER_GRADE_SUCCESS =
  "FETCH_OTHERMASTER_GRADE_SUCCESS";
export const FETCH_OTHERMASTER_GRADE_FAIL = "FETCH_OTHERMASTER_GRADE_FAIL";

export const FETCH_OTHERMASTER_QLF_START = "FETCH_OTHERMASTER_QLF_START";
export const FETCH_OTHERMASTER_QLF_SUCCESS = "FETCH_OTHERMASTER_QLF_SUCCESS";
export const FETCH_OTHERMASTER_QLF_FAIL = "FETCH_OTHERMASTER_QLF_FAIL";

export const FETCH_OTHERMASTER_SEQ_START = "FETCH_OTHERMASTER_SEQ_START";
export const FETCH_OTHERMASTER_SEQ_SUCCESS = "FETCH_OTHERMASTER_SEQ_SUCCESS";
export const FETCH_OTHERMASTER_SEQ_FAIL = "FETCH_OTHERMASTER_SEQ_FAIL";

export const FETCH_OTHERMASTER_CATEGORY_START =
  "FETCH_OTHERMASTER_CATEGORY_START";
export const FETCH_OTHERMASTER_CATEGORY_SUCCESS =
  "FETCH_OTHERMASTER_CATEGORY_SUCCESS";
export const FETCH_OTHERMASTER_CATEGORY_FAIL =
  "FETCH_OTHERMASTER_CATEGORY_FAIL";

export const FETCH_OTHERMASTER_EXPERIENCE_START =
  "FETCH_OTHERMASTER_EXPERIENCE_START";
export const FETCH_OTHERMASTER_EXPERIENCE_SUCCESS =
  "FETCH_OTHERMASTER_EXPERIENCE_SUCCESS";
export const FETCH_OTHERMASTER_EXPERIENCE_FAIL =
  "FETCH_OTHERMASTER_EXPERIENCE_FAIL";

export const FETCH_OTHERMASTER_DESIGNATIONS_START =
  "FETCH_OTHERMASTER_DESIGNATIONS_START";
export const FETCH_OTHERMASTER_DESIGNATIONS_SUCCESS =
  "FETCH_OTHERMASTER_DESIGNATIONS_SUCCESS";
export const FETCH_OTHERMASTER_DESIGNATIONS_FAIL =
  "FETCH_OTHERMASTER_DESIGNATIONS_FAIL";

export const FETCH_OTHERMASTER_ORDERSTATUS_START =
  "FETCH_OTHERMASTER_ORDERSTATUS_START";
export const FETCH_OTHERMASTER_ORDERSTATUS_SUCCESS =
  "FETCH_OTHERMASTER_ORDERSTATUS_SUCCESS";
export const FETCH_OTHERMASTER_ORDERSTATUS_FAIL =
  "FETCH_OTHERMASTER_ORDERSTATUS_FAIL";

export const FETCH_OTHERMASTER_SUPPORTSTATUS_START =
  "FETCH_OTHERMASTER_SUPPORTSTATUS_START";
export const FETCH_OTHERMASTER_SUPPORTSTATUS_SUCCESS =
  "FETCH_OTHERMASTER_SUPPORTSTATUS_SUCCESS";
export const FETCH_OTHERMASTER_SUPPORTSTATUS_FAIL =
  "FETCH_OTHERMASTER_SUPPORTSTATUS_FAIL";

export const SAVE_CHANGEPASSWORD_START = "SAVE_CHANGEPASSWORD_START";
export const SAVE_CHANGEPASSWORD_SUCCESS = "SAVE_CHANGEPASSWORD_SUCCESS";
export const SAVE_CHANGEPASSWORD_FAIL = "SAVE_CHANGEPASSWORD_FAIL";

//20200223
export const FETCH_PACKAGE_START = "FETCH_PACKAGE_START";
export const FETCH_PACKAGE_SUCCESS = "FETCH_PACKAGE_SUCCESS";
export const FETCH_PACKAGE_FAIL = "FETCH_PACKAGE_FAIL";
//20200223

//20200404
export const FETCH_USERMENU_START = "FETCH_USERMENU_START";
export const FETCH_USERMENU_SUCCESS = "FETCH_USERMENU_SUCCESS";
export const FETCH_USERMENU_FAIL = "FETCH_USERMENU_FAIL";
//20200404

export const FETCH_SYSSEQUENCECONFIG_START = "FETCH_SYSSEQUENCECONFIG_START";
export const FETCH_SYSSEQUENCECONFIG_SUCCESS =
  "FETCH_SYSSEQUENCECONFIG_SUCCESS";
export const FETCH_SYSSEQUENCECONFIG_FAIL = "FETCH_SYSSEQUENCECONFIG_FAIL";

export const FETCH_REPORT_DATA_KEYS_START = "FETCH_REPORT_DATA_KEYS_START";
export const FETCH_REPORT_DATA_KEYS_SUCCESS = "FETCH_REPORT_DATA_KEYS_SUCCESS";
export const FETCH_REPORT_DATA_KEYS_FAIL = "FETCH_REPORT_DATA_KEYS_FAIL";

export const FETCH_KOTMASTERSTATUS_START = "FETCH_KOTMASTERSTATUS_START";
export const FETCH_KOTMASTERSTATUS_SUCCESS = "FETCH_KOTMASTERSTATUS_SUCCESS";
export const FETCH_KOTMASTERSTATUS_FAIL = "FETCH_KOTMASTERSTATUS_FAIL";

export const FETCH_KEYBOARD_HOTKEY_CONFIG_START =
  "FETCH_KEYBOARD_HOTKEY_CONFIG_START";
export const FETCH_KEYBOARD_HOTKEY_CONFIG_SUCCESS =
  "FETCH_KEYBOARD_HOTKEY_CONFIG_SUCCESS";
export const FETCH_KEYBOARD_HOTKEY_CONFIG_FAIL =
  "FETCH_KEYBOARD_HOTKEY_CONFIG_FAIL";

export const FETCH_OTHERMASTER_USERGROUP_START =
  "FETCH_OTHERMASTER_USERGROUP_START";
export const FETCH_OTHERMASTER_USERGROUP_SUCCESS =
  "FETCH_OTHERMASTER_USERGROUP_SUCCESS";
export const FETCH_OTHERMASTER_USERGROUP_FAIL =
  "FETCH_OTHERMASTER_USERGROUP_FAIL";

export const FETCH_OTHERMASTER_INCOME_START = "FETCH_OTHERMASTER_INCOME_START";
export const FETCH_OTHERMASTER_INCOME_SUCCESS =
  "FETCH_OTHERMASTER_INCOME_SUCCESS";
export const FETCH_OTHERMASTER_INCOME_FAIL = "FETCH_OTHERMASTER_INCOME_FAIL";

export const FETCH_OTHERMASTER_EXPENSE_START =
  "FETCH_OTHERMASTER_EXPENSE_START";
export const FETCH_OTHERMASTER_EXPENSE_SUCCESS =
  "FETCH_OTHERMASTER_EXPENSE_SUCCESS";
export const FETCH_OTHERMASTER_EXPENSE_FAIL = "FETCH_OTHERMASTER_EXPENSE_FAIL";

export const FETCH_OTHERMASTER_SUPPTYP_START =
  "FETCH_OTHERMASTER_SUPPTYP_START";
export const FETCH_OTHERMASTER_SUPPTYP_SUCCESS =
  "FETCH_OTHERMASTER_SUPPTYP_SUCCESS";
export const FETCH_OTHERMASTER_SUPPTYP_FAIL = "FETCH_OTHERMASTER_SUPPTYP_FAIL";

export const FETCH_OTHERMASTER_REASONSMASTER_START =
  "FETCH_OTHERMASTER_REASONSMASTER_START";
export const FETCH_OTHERMASTER_REASONSMASTER_SUCCESS =
  "FETCH_OTHERMASTER_REASONSMASTER_SUCCESS";
export const FETCH_OTHERMASTER_REASONSMASTER_FAIL =
  "FETCH_OTHERMASTER_REASONSMASTER_FAIL";

export const FETCH_ROUNDOFF_CONFIG_START = "FETCH_ROUNDOFF_CONFIG_START";
export const FETCH_ROUNDOFF_CONFIG_SUCCESS = "FETCH_ROUNDOFF_CONFIG_SUCCESS";
export const FETCH_ROUNDOFF_CONFIG_FAIL = "FETCH_ROUNDOFF_CONFIG_FAIL";

export const VALIDATE_COMPANY_START = "VALIDATE_COMPANY_START";
export const VALIDATE_COMPANY_SUCCESS = "VALIDATE_COMPANY_SUCCESS";
export const VALIDATE_COMPANY_FAIL = "VALIDATE_COMPANY_FAIL";

export const SET_COMPANY_CODE = "SET_COMPANY_CODE";
